version: '3.7'

services:
  app:
    container_name: 'fintracer-app'
    build: .
    command: sh -c "pnpm prisma generate && pnpm dev"
    ports:
      - 3333:3333
    depends_on:
      - fintracer-pg
    environment:
      - DATABASE_URL=postgresql://docker:docker@fintracer-pg:5432/fintracerdb?schema=public
      - JWT_SECRET=test

    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    networks:
      - app-net

  fintracer-pg:
    container_name: 'fintracer-pg'
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fintracerdb
    volumes:
      - fintracer_pg_data:/bitnami/postgresql
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  fintracer_pg_data:
